### ISSUE TITLE
Regions are not updated when new SVG file is uploaded

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/wagtail-svgmap#5]
Steps to reproduce:
1. Add an image map. Save.
2. Change the SVG file ids.
3. Replace the file in the image map. Save.
4. Regions are not updated.

Expected behavior:

Regions are updated automatically based on the ids of the new SVG file.

**Comment by akx** [comment]
Ah, I didn't think about replacing the SVG file in a pre-existing instance. Will fix.

**Comment by akx** [comment]
This is resolved in #6.
